<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="7020761SMZEALO7" name="launchTest.LaunchApiRiesgo" tests="2" failures="0" timestamp="2022-09-09T14:28:13 GMT-05:00" time="0.886" errors="1">
  <testcase name="DXCExec" time="0.000" classname="launchTest.LaunchApiRiesgo">
    <skipped/>
  </testcase> <!-- DXCExec -->
  <system-out/>
  <testcase name="beforeClass" time="0.886" classname="launchTest.LaunchApiRiesgo">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at sun.awt.SunToolkit.getImageFromHash(Unknown Source)
at sun.awt.SunToolkit.getImage(Unknown Source)
at dxc.util.DXCUtil.getProviderIconImage(DXCUtil.java:71)
at dxc.util.ConsoleWindow.<init>(ConsoleWindow.java:64)
at dxc.execution.BaseTestNG.beforeClass(BaseTestNG.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at CreadorJarTest.CrearJarDaviviendaTest.main(CrearJarDaviviendaTest.java:48)
]]>
    </error>
  </testcase> <!-- beforeClass -->
  <system-out/>
</testsuite> <!-- launchTest.LaunchApiRiesgo -->
